export interface AllOrdersPnL {
  id?: number;
  sales_status: string;
  sales_channel: string | null;
  fulfillment_channel: string | null;
  product_type: string | null;
  payment_status: string;
  return_status: string | null;
  amazon_order_id: string | null;
  sku: string | null;
  quantity: number | null;
  purchase_date_pst_pdt: string | null;
  data_month_last_day: string;
  currency: string | null;
  item_price: string | null;
  shipping_price: string | null;
  gift_wrap_price: string | null;
  item_tax: string | null;
  shipping_tax: string | null;
  gift_wrap_tax: string | null;
  item_promotion_discount: string | null;
  ship_promotion_discount: string | null;
  commission: string | null;
  sponsored_products_charge: string | null;
  sales_tax_service_fee: string | null;
  digital_services_fee: string | null;
  FBA_fulfillment_fee: string | null;
  FBA_inbound_transportation_fee: string | null;
  FBA_storage_fee: string | null;
  FBM_shipping_commission: string | null;
  subscription_fee: string | null;
  order_settlement_id: string | null;
  order_deposit_date_pst_pdt: string | null;
  order_posted_date_pst_pdt: string | null;
  non_order_settlement_id: string | null;
  non_order_deposit_date_pst_pdt: string | null;
  non_order_posted_date_pst_pdt: string | null;
  statements_item_price: string | null;
  statements_shipping_price: string | null;
  statements_shipping_chargeback: string | null;
  statements_gift_wrap_price: string | null;
  statements_gift_wrap_chargeback: string | null;
  statements_item_tax: string | null;
  statements_shipping_tax: string | null;
  statements_gift_wrap_tax: string | null;
  statements_item_promotion_discount: string | null;
  statements_ship_promotion_discount: string | null;
  statements_promotion_deal_coupon_fees_allocated: string | null;
  statements_commission: string | null;
  statements_sponsored_products_charge_allocated: string | null;
  statements_sales_tax_service_fee: string | null;
  statements_digital_services_fee: string | null;
  statements_FBA_fulfillment_fee: string | null;
  statements_FBA_storage_fee_allocated: string | null;
  statements_FBM_shipping_commission: string | null;
  statements_subscription_fee_allocated: string | null;
  statements_marketplace_facilitator_tax_principal: string | null;
  statements_marketplace_facilitator_tax_shipping: string | null;
  statements_order_other: string | null;
  return_settlement_id: string | null;
  return_deposit_date_pst_pdt: string | null;
  return_posted_date_pst_pdt: string | null;
  returns_item_price: string | null;
  returns_item_price_goodwill_adjustment: string | null;
  returns_shipping_price: string | null;
  returns_shipping_chargeback: string | null;
  returns_gift_wrap_price: string | null;
  returns_gift_wrap_chargeback: string | null;
  returns_item_tax: string | null;
  returns_shipping_tax: string | null;
  returns_gift_wrap_tax: string | null;
  returns_item_promotion_discount: string | null;
  returns_ship_promotion_discount: string | null;
  returns_commission: string | null;
  returns_digital_services_fee: string | null;
  returns_FBM_shipping_commission: string | null;
  returns_marketplace_facilitator_tax_principal: string | null;
  returns_marketplace_facilitator_tax_shipping: string | null;
  returns_refund_commission: string | null;
  statements_return_other: string | null;
  statements_other_allocated: string | null;
  statements_promotion_deal_coupon_fees: string | null;
  statements_sponsored_products_charge: string | null;
  statements_FBA_storage_fee: string | null;
  statements_subscription_fee: string | null;
  statements_other: string | null;
  statements_non_sku_adjustments: string | null;
}

export interface LatestSalesRecord {
  amazon_order_id: string;
  purchase_date_pst_pdt: string;
}

export interface LatestStatementRecord {
  settlement_id: string;
  deposit_date_pst_pdt: string;
  total_amount: string;
} 