
-- Table: AllOrdersPnL
CREATE TABLE AllOrdersPnL (
    id SERIAL PRIMARY KEY,
    sales_status TEXT NOT NULL, 
    sales_channel TEXT, 
    fulfillment_channel TEXT, 
    product_type TEXT, 
    payment_status TEXT NOT NULL, 
    return_status TEXT,
    amazon_order_id TEXT, 
    sku TEXT,
    quantity INTEGER, 
    purchase_date_pst_pdt TIMESTAMP,  
    data_month_last_day DATE NOT NULL,
    currency TEXT,
    item_price NUMERIC(10, 2), 
    shipping_price NUMERIC(10, 2), 
    gift_wrap_price NUMERIC(10, 2),
    item_tax NUMERIC(10, 2), 
    shipping_tax NUMERIC(10, 2), 
    gift_wrap_tax NUMERIC(10, 2),
    item_promotion_discount NUMERIC(10, 2), 
    ship_promotion_discount NUMERIC(10, 2),
    commission NUMERIC(10, 2), 
    sponsored_products_charge NUMERIC(10, 2),
    sales_tax_service_fee NUMERIC(10, 2), 
    marketplace_facilitator_tax_principal NUMERIC(10, 2),
    marketplace_facilitator_tax_shipping NUMERIC(10, 2),
    digital_services_fee NUMERIC(10, 2),
    FBA_fulfillment_fee NUMERIC(10, 2), 
    FBA_inbound_transportation_fee NUMERIC(10, 2), 
    FBA_storage_fee NUMERIC(10, 2),
    FBM_shipping_commission NUMERIC(10, 2),
    subscription_fee NUMERIC(10, 2),
    order_settlement_id TEXT,
    order_deposit_date_pst_pdt TIMESTAMP,
    order_posted_date_pst_pdt TIMESTAMP,
    non_order_settlement_id TEXT,
    non_order_deposit_date_pst_pdt TIMESTAMP,
    non_order_posted_date_pst_pdt TIMESTAMP,
    statements_item_price NUMERIC(10, 2), 
    statements_shipping_price NUMERIC(10, 2), 
    statements_shipping_chargeback NUMERIC(10, 2), 
    statements_gift_wrap_price NUMERIC(10, 2), 
    statements_gift_wrap_chargeback NUMERIC(10, 2),
    statements_item_tax NUMERIC(10, 2), 
    statements_shipping_tax NUMERIC(10, 2), 
    statements_gift_wrap_tax NUMERIC(10, 2),
    statements_item_promotion_discount NUMERIC(10, 2),
    statements_ship_promotion_discount NUMERIC(10, 2), 
    statements_promotion_deal_coupon_fees_allocated NUMERIC(10, 2),
    statements_commission NUMERIC(10, 2), 
    statements_sponsored_products_charge_allocated NUMERIC(10, 2),
    statements_sales_tax_service_fee NUMERIC(10, 2), 
    statements_marketplace_facilitator_tax_principal NUMERIC(10, 2),	
    statements_marketplace_facilitator_tax_shipping NUMERIC(10, 2),
    statements_digital_services_fee NUMERIC(10, 2),
    statements_FBA_fulfillment_fee NUMERIC(10, 2), 
    statements_FBA_storage_fee_allocated NUMERIC(10, 2),
    statements_FBM_shipping_commission NUMERIC(10, 2),
    statements_subscription_fee_allocated NUMERIC(10, 2),
    statements_order_other NUMERIC(10, 2),
    return_settlement_id TEXT, 
    return_deposit_date_pst_pdt TIMESTAMP,
    return_posted_date_pst_pdt TIMESTAMP,
    returns_item_price NUMERIC(10, 2), 
    returns_item_price_goodwill_adjustment NUMERIC(10, 2), 
    returns_shipping_price NUMERIC(10, 2), 
    returns_shipping_chargeback NUMERIC(10, 2), 
    returns_gift_wrap_price NUMERIC(10, 2), 
    returns_gift_wrap_chargeback NUMERIC(10, 2),
    returns_item_tax NUMERIC(10, 2), 
    returns_shipping_tax NUMERIC(10, 2), 
    returns_gift_wrap_tax NUMERIC(10, 2),
    returns_item_promotion_discount NUMERIC(10, 2), 
    returns_ship_promotion_discount NUMERIC(10, 2),
    returns_commission NUMERIC(10, 2),
    returns_digital_services_fee NUMERIC(10, 2),
    returns_FBM_shipping_commission NUMERIC(10, 2),
    returns_marketplace_facilitator_tax_principal NUMERIC(10, 2),
    returns_marketplace_facilitator_tax_shipping NUMERIC(10, 2),
    returns_refund_commission NUMERIC(10, 2),
    statements_return_other NUMERIC(10, 2),
    statements_other_allocated NUMERIC(10, 2),
    statements_promotion_deal_coupon_fees NUMERIC(10, 2),
    statements_sponsored_products_charge NUMERIC(10, 2),
    statements_FBA_storage_fee NUMERIC(10, 2),
    statements_subscription_fee NUMERIC(10, 2),
    statements_other NUMERIC(10, 2),
    statements_non_sku_adjustments NUMERIC(10, 2)
);
